language: node_js
node_js:
- 7
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_3f358765692c_key -iv $encrypted_3f358765692c_iv
  -in .coveralls.yml.enc -out .coveralls.yml -d
install:
- npm set progress=false
- npm install
script:
- npm run test
- npm run build
- npm publish
deploy:
  provider: npm
  email: "YOUR_EMAIL_ADDRESS"
  api_key: "YOUR_API_KEY"
env:
  global:
  - secure: Zgg/SoRQF29osRiEgMJuZlji3qdWVJOu8rzLWTiZKNsbeloRhPctrIQpHSc8XzOu+uBYgC5RDbh9hhRAIlZisu29z+QsuXN/BGcBCB378343vJmkQCFua7u4N12onFA4KWrKIAemsqlvf4olUycsUumQiPB1picDg45A5U7ymZcXg39VkMfffUZ3vTvAhxcYtCcVSVKknpQgBGQE6B+q/gVYF/uU/dBMFQ13rBfNmFr9xMH8lJCaM3Trx+HLZwYlDf1GJptTE5pWL4yEEEK73OrmFPDuQDCHe8gIczLcgcQx77ydpAAI3PVtG9WLOeWkxqSL2HX2Rt8tbbgJ/HkQARq1B7+GAbCIMEjGmh7j1I+y5VOpoGDFNupO//UpHN/qnR5RPsamVuqmf8BKRHFksmovpiZKG/39bgYst+O7yJj89w3pJk++6DMsorwznkWmOIn7hV/j8j8B35bE41TPaZlM6bQgDNZolxh1M5eme7ZLuSUXwI1oGskatdeKn4C3oTn9k1k3MMUsKIt1cLobdqDTqocazJnNOfGGtuCUzjcYKktotnbFXz0PhYnL/PVkEW9BP/Rpo32V1++YNy++aKVqVzaWNVaET1hMjgmu+C9k8TzdoN8M36mF/CgbnzYDf/l2rQwM+SB9bEwKHdQJPqdgpyZ23SN1yiFQpx5On2s=
  - secure: FGRQHalrMK+LcxUbsH7Sus1BPNkNJv0TVDGfMaq3IovAFbasN4JtCePCNDyHmzB/rAIYQM5qdke0B07KCVmK16sHvOudigR22gW/YHc28aGW6ra86SXEJdCCryzzTcgXqt0BYi2F8PWf0hmdl/eN3UcJJjS1hVNQYyqIKfSv/JfURea2lbTsKumCS5PgGKQlbIvgrIvEoJdWXL3ZjWUbflPaKioryLIOz6YqXdaBfD5Ke0/Xlk+lwHpl9tA+GVOOJNukVDKGazkAsG27rlidWjF0IAlj7SUtjAxAZh670TGpPR8yYYnGs37jBv26I4TpD+W8ms34TdBRRd0rQW55uplkOMxjba6Kd/RUKpK/Y95fpEemeCRyK66Z0dWCHFRwemqE/9jh1MxgfznlNgp5ipqGZy316gQYc6eiSDG2q3jQUd8nmMk4+2TVm+ZN0+WdUSvq5V4i91uvJDSe/K3pHGKjf5kbm6uSWmORDn0e1a1JJ/VSzej9GbblccutkwMGer2wuKpSYBAWwGJ5pztuklqJ3JdEO4sZDx+8BwcNjDlaWmfvUSihh/4o+qHWJGVa2fz8m97d8mRWJ5tL8hmZ2WHGs4zEq2FVNH1tTqrqmYo4xJllKwD55kS2R7BNTeYYPVH1tqhkMudTT6VQysyIaf3EDHEuU4uqJL9B9AUgGD0=
  - secure: q239TxpdhCWpjVDie0LGZneq5Ux4UDclFWZaodwkH8pF4skU3zQ/3gcXJHox1I17Nxp/3eNlgdxEzLJrtLGgOqNL0n4Ytkcys2Jw6CNcoD/DMhWg6tOqKyPq4zzzXXgNv2Va9bEnQjCJe/gv6Dg1KqxfyDun/MfL9qFKPSUCHROzI5znIlyUshfA5vDiTt0sJyO+J61QfYQNG1HSk1D0pkMApRC49wYwoHjFx+AslBiLEG+XH0v9n8q8c9HLDZROygLcTCUzmBNflYojFJ5KMsX/QrsZCh+ImMHDg2ciAN35eIFbYZNAp1JWnXmga0SkiAsHnqS2Gj8bw3fgOdraofqaqH94AQFO+qqE3HrG6Y5BiC/DheoStlF6cD0pGlEHqDqIJjntmnUhc7s93wikdVK6YZZKEnv1Kh+ePsCvdCRzF4Z/mO9yBoslpPVsADUc8YYpyXADexuwJWFv0hZU9+lxyD/GCxlB1uhBzKtxUIo6Z/yKumvX7F86Znk8LFKnp3c3j8OhkGEs4zqSihZvCRv+SVZ9Acoj3oQd1bjV0101PXsqcW+qOs1G7Tbyj7mJjJ/6QtXqQ8AdxEJM29WkhHnggLLXQbNfsEP5pliVMuzVDTHVU8tdZ21fjYnWo05b2kGkPYyq3RxmPkVFOf1dF6AuNUTycYLzQXMJ/le0+bo=
  - secure: nVoh7fJ6HOUGxhcT42SQPsIUIwAMXoAauwdQRCtqfL5kH1f4kpvb8CEv352qd28MeXe/qDgqJ94azluvgWxk+ftHtYegrt7oojI9tsbvpw8A0OrWmojIPlivZr61u/fwh0rCMyt3PFF5YqNR98DaXnY9Qud3iGuw3zpoYnUjM5sOa+gBHNr7nQoIr816ffMja7YR+FMlYPCdhG5ho/mm3C0DxRuC+5eZruYIaA2J/wU47Ua4nOC+cJWeNP81q0kh1YChdr5B/6N+aNH2JgITqm1XX1u1+oV4Rx4WjHDhg2nECA4pthQt/JXR5hp3Qdx01517OrgM6pxStzDzn4r9xX0b2LOFpkgabopZw2E0kRuJIuARQd1tz2rvqxIS3sncf0Hv9GktBXD2/F97anEVlyXVUkXntIQB3sB/ZIFwNdc3mefejW5YYpS6gHr1ND4Kj7ukOrhEr7X1XRlc5Otss8S8XgvamO4JlNaS/DfldjFIupXvTlp+ps1SEVyqDACo//hVL+KBpZhJfpLRu8BkJZtQc0hv8SMx0mSDEnaeCKsJ5/Cq3WH+AmQUK21JX0jkwTYVxzv5RyHxN4zqbd+A3aGstsGUTnVtTxJt5L6MJmFIiYebTgL+UX+Owrt2k/OlXCqkY5sY+aOSZ+1dZ+YisbFZL6sLRxGb5e2Ou2QKBBY=

